# Generated by Django 5.2.2 on 2025-06-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название концепции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Концепция',
                'verbose_name_plural': 'Концепции',
            },
        ),
        migrations.CreateModel(
            name='HistoricalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, verbose_name='Исторический период')),
                ('description', models.TextField(verbose_name='Описание исторического контекста')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_contexts', to='kant_duty.concept')),
            ],
            options={
                'verbose_name': 'Исторический контекст',
                'verbose_name_plural': 'Исторические контексты',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('source', models.CharField(max_length=200, verbose_name='Источник')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='kant_duty.concept')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название источника')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='kant_duty.concept')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
    ]
